/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import javax.swing.JColorChooser;


/**
 *
 * @author Joana
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private Lienzo lienzo;
    private Color colorActual = Color.BLACK;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
            /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        lienzo = new Lienzo();
        lienzo.setBounds(0,100,800,495);
        add(lienzo);
        
        setSize(800, 600);
        setLayout(null);
        setLocationRelativeTo(null);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pinceles = new javax.swing.ButtonGroup();
        jLabelPincel = new javax.swing.JLabel();
        rbPunto = new javax.swing.JRadioButton();
        rbRecta = new javax.swing.JRadioButton();
        rbCirculo = new javax.swing.JRadioButton();
        rbPoligonoRegular = new javax.swing.JRadioButton();
        rbPoligonoIrregular = new javax.swing.JRadioButton();
        sBarraPoligono = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        cbRelleno = new javax.swing.JComboBox<>();
        rbLapiz = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbMenu = new javax.swing.JMenu();
        jcbMenuNuevo = new javax.swing.JCheckBoxMenuItem();
        jcbMenuCargar = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        mbArchivo = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelPincel.setText("Elije pincel");

        Pinceles.add(rbPunto);
        rbPunto.setText("Punto");
        rbPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPuntoActionPerformed(evt);
            }
        });

        Pinceles.add(rbRecta);
        rbRecta.setText("Recta");
        rbRecta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRectaActionPerformed(evt);
            }
        });

        Pinceles.add(rbCirculo);
        rbCirculo.setText("Círculo");
        rbCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCirculoActionPerformed(evt);
            }
        });

        Pinceles.add(rbPoligonoRegular);
        rbPoligonoRegular.setText("Polígono Regular");
        rbPoligonoRegular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPoligonoRegularActionPerformed(evt);
            }
        });

        Pinceles.add(rbPoligonoIrregular);
        rbPoligonoIrregular.setText("Polígono Irregular");

        jLabel1.setText("Lados polígono:");

        cbRelleno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Relleno", "Con Relleno" }));
        cbRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRellenoActionPerformed(evt);
            }
        });

        Pinceles.add(rbLapiz);
        rbLapiz.setText("Lapíz");
        rbLapiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLapizActionPerformed(evt);
            }
        });

        jButton1.setText("Elige Color");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mbMenu.setText("Menú");

        jcbMenuNuevo.setSelected(true);
        jcbMenuNuevo.setText("Nuevo");
        mbMenu.add(jcbMenuNuevo);

        jcbMenuCargar.setSelected(true);
        jcbMenuCargar.setText("Cargar");
        jcbMenuCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMenuCargarActionPerformed(evt);
            }
        });
        mbMenu.add(jcbMenuCargar);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("SVG");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        mbMenu.add(jCheckBoxMenuItem1);

        jMenuBar1.add(mbMenu);

        mbArchivo.setText("Archivo");
        jMenuBar1.add(mbArchivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbPunto)
                            .addComponent(rbRecta))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbPoligonoIrregular)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbPoligonoRegular)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbLapiz)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(sBarraPoligono, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbCirculo)
                                .addGap(18, 18, 18)
                                .addComponent(cbRelleno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelPincel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPincel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbPunto)
                            .addComponent(rbPoligonoRegular)
                            .addComponent(rbLapiz))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sBarraPoligono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbRecta)
                    .addComponent(rbPoligonoIrregular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCirculo)
                    .addComponent(cbRelleno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(386, 386, 386))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbRectaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRectaActionPerformed
    lienzo.usarRecta();
        
        
        
        
    }//GEN-LAST:event_rbRectaActionPerformed

    private void rbCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCirculoActionPerformed
    lienzo.usarCirculo();



    }//GEN-LAST:event_rbCirculoActionPerformed

    private void jcbMenuCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMenuCargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMenuCargarActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void rbPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPuntoActionPerformed
    lienzo.usarPunto();



    }//GEN-LAST:event_rbPuntoActionPerformed

    private void rbPoligonoRegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPoligonoRegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPoligonoRegularActionPerformed

    private void rbLapizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLapizActionPerformed
    lienzo.usarLapiz();
    }//GEN-LAST:event_rbLapizActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Color color = JColorChooser.showDialog(this, "Selecciona un color", colorActual);
        
        if (color != null){
            colorActual = color;
            lienzo.setColorActual(colorActual);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRellenoActionPerformed
        
        if (lienzo != null) {
        boolean conRelleno = cbRelleno.getSelectedItem().toString().equals("Con Relleno");
        lienzo.setRellenoCirculo(conRelleno);
    }


    }//GEN-LAST:event_cbRellenoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Pinceles;
    private javax.swing.JComboBox<String> cbRelleno;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPincel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JCheckBoxMenuItem jcbMenuCargar;
    private javax.swing.JCheckBoxMenuItem jcbMenuNuevo;
    private javax.swing.JMenu mbArchivo;
    private javax.swing.JMenu mbMenu;
    private javax.swing.JRadioButton rbCirculo;
    private javax.swing.JRadioButton rbLapiz;
    private javax.swing.JRadioButton rbPoligonoIrregular;
    private javax.swing.JRadioButton rbPoligonoRegular;
    private javax.swing.JRadioButton rbPunto;
    private javax.swing.JRadioButton rbRecta;
    private javax.swing.JSlider sBarraPoligono;
    // End of variables declaration//GEN-END:variables
}
