/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Joana
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        Lienzo lienzo = new Lienzo();
        lienzo.setBounds(0,100,800,500);
        add(lienzo);
        
        setSize(800, 600);
        setLayout(null);
        setLocationRelativeTo(null);
        setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pinceles = new javax.swing.ButtonGroup();
        jLabelPincel = new javax.swing.JLabel();
        rbPunto = new javax.swing.JRadioButton();
        rbRecta = new javax.swing.JRadioButton();
        rbCirculo = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbMenu = new javax.swing.JMenu();
        jcbMenuNuevo = new javax.swing.JCheckBoxMenuItem();
        jcbMenuCargar = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        mbArchivo = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelPincel.setText("Elije pincel");

        rbPunto.setText("Punto");

        rbRecta.setText("Recta");
        rbRecta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRectaActionPerformed(evt);
            }
        });

        rbCirculo.setText("Círculo");
        rbCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCirculoActionPerformed(evt);
            }
        });

        mbMenu.setText("Menú");

        jcbMenuNuevo.setSelected(true);
        jcbMenuNuevo.setText("Nuevo");
        mbMenu.add(jcbMenuNuevo);

        jcbMenuCargar.setSelected(true);
        jcbMenuCargar.setText("Cargar");
        jcbMenuCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMenuCargarActionPerformed(evt);
            }
        });
        mbMenu.add(jcbMenuCargar);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("SVG");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        mbMenu.add(jCheckBoxMenuItem1);

        jMenuBar1.add(mbMenu);

        mbArchivo.setText("Archivo");
        jMenuBar1.add(mbArchivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbPunto)
                    .addComponent(jLabelPincel)
                    .addComponent(rbRecta)
                    .addComponent(rbCirculo))
                .addContainerGap(582, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabelPincel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbPunto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbRecta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCirculo)
                .addGap(387, 387, 387))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbRectaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRectaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRectaActionPerformed

    private void rbCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCirculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCirculoActionPerformed

    private void jcbMenuCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMenuCargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMenuCargarActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Pinceles;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabelPincel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JCheckBoxMenuItem jcbMenuCargar;
    private javax.swing.JCheckBoxMenuItem jcbMenuNuevo;
    private javax.swing.JMenu mbArchivo;
    private javax.swing.JMenu mbMenu;
    private javax.swing.JRadioButton rbCirculo;
    private javax.swing.JRadioButton rbPunto;
    private javax.swing.JRadioButton rbRecta;
    // End of variables declaration//GEN-END:variables
}
